{% set version = "2.2.6" %}

package:
  name: secapr
  version: {{ version }}

source:
  url: https://github.com/AntonelliLab/seqcap_processor/archive/v{{ version }}.tar.gz
  sha256: 63a67d6bc5d139b2910e562dc7969e7c8374c01720af5319a0f7a9d06c5983c0

build:
  noarch: generic
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - secapr = secapr.__main__:main

requirements:
  host:
    - python
    - pip

  run:
    - python=3.8
    - pandas
    - matplotlib-base
    - biopython
    - trimmomatic
    - fastqc
    - fastp=0.23
    - spades=3.15.2
    - blast
    - mafft
    - muscle
    - emboss
    - bwa
    - samtools==1.3.1
    - trimal

test:
  imports:
    - secapr
  commands:
    - secapr --version

about:
  home: 'https://github.com/AntonelliLab/seqcap_processor'
  license: MIT
  license_file: LICENSE
  summary: 'Process sequence-capture FASTQ files into alignments for phylogenetic analyses. Integrates allele phasing.'
